// The achievement condition and the reward are system-owned: they are authored / rolled and
// surfaced by system-owned UI (the card's 達成条件 element + reward chip and the conversation
// detail popup), never by the offer's generated prose. A generated field that smuggles in a
// 達成条件 or 報酬 statement lets the model fake the system contract on screen — the exact
// mismatch that made a screen "達成条件: ..." diverge from the hidden judgment condition
// (offer-condition-mismatch-investigation). The offer prompts already instruct the model not
// to write these; this is the gate that enforces it.
//
// Shared by the errand and study circle gates so both pipelines reject the identical wording on
// every field of both the skeleton adopt-gate and the final gate. The check is a plain substring
// scan (not a boundary match): the two terms are contract nouns that have no innocent use inside
// an offer's own-voice prose, and a stray occurrence is regenerated by the existing bounded retry.
export const FORBIDDEN_OFFER_CONTRACT_TERMS = Object.freeze(['達成条件', '報酬']);

// Returns the first forbidden contract term found in the value, or null when the value carries
// neither. Callers throw with their own generation-error factory so the errand / study circle
// error codes stay distinct.
export function forbiddenOfferContractTerm(value) {
  const text = String(value ?? '');
  for (const term of FORBIDDEN_OFFER_CONTRACT_TERMS) {
    if (text.includes(term)) return term;
  }
  return null;
}
